@startuml
start

:发起部门变更流程;

: scc审批节点通过 ;
floating note right: 包括新增和变更

if(判断部门类型) then(非门店)

    :财务成本中心审批节点审批;
    floating note left: 需要强制填写成本中心编号（必填）code\n通过配置工作流"ps-成本中心"suggest获取
    :走后续节点流转逻辑;
    :最后一个几点审批通过;
    :将财务成本中心审批节点填写的"成本中心编号"，\n填写到ps接口的入参中;

else(门店)

    :走后续节点流转逻辑;
    :最后一个几点审批通过;
    if(是否新增部门)then(是)
        :将门店编号，填写到ps接口的"成本中心编号"字段上;
    else(否)
    endif

endif

:调用ps部门变更接口;

stop
@enduml