#活动图 (新语法)

当前活动图 (activity diagram) 的语法有诸多限制和缺点,比如代码难以维护。
所以从 V7947 开始提出一种全新的、更好的语法格式和软件实现供用户使用 (beta 版)。
就像序列图一样,新的软件实现的另一个优点是它不再依赖与 Graphviz。
新的语法将会替换旧的语法。
然而考虑到兼容性,旧的语法仍被能够使用以确保向前兼容。
但是我们鼓励用户使用新的语法格式。

@startuml
:Hello world;
:This is on defined on
several **lines**;
@enduml
