#进入和发出消息

如果只想关注部分图示,你可以使用进入和发出箭头。
使用方括号 [和] 表示图示的左、右两侧。

@startuml

[-> A : DoWork
activate A

A -> A : internal call
activate A

A ->] : <<RequestCreated>>

]--> A : RequestCreated
deactivate A
A -->[ : Done
deactivate A

@enduml