@startuml

start

:获取门店员工信息;

if(入店日期 != null && 离店日期 != null )then(yes)
    if(入店日期 == 离店日期)then(yes)
        :可用时间区间为空;
    else if(入店日期 <= 离店日期)
        :可用时间区间为空 [入店日期早7点，离店日期早7点];
    else
        :可用时间区间为空 [负无穷，离店店日期早7点]，[入店日期早7点,正无穷];
    endif
else if(入店日期 != null)
    :可用时间区间为空 [入店日期早7点,正无穷];
else if(离店日期 != null)
    :可用时间区间为空 [负无穷，离店店日期早7点];
else if(isOnShop状态为参与排班)
    :可用时间区间为空 [负无穷，正无穷];
else
    :可用时间区间为空;
endif

stop

@enduml