@startuml

|考勤系统|
start
:mq消息触发班次匹配逻辑;
|打卡系统|
:获取打卡班次（门店code，上下班打卡时间，打卡类型）;

|考勤系统|

if(检验打卡班次是否消费过)then(否)

    :获取打卡匹配规则;

    if(判断匹配规则)then(正常门店打卡匹配规则)

        partition 班次匹配 {
            :拉取和打卡班次有交集的考勤班次;
            :匹配班次;
            note left:班次匹配规则case
            if(匹配后班次为空)then(是)
                :创建空班次;
                :生成考勤打卡记录;
            else(否)
                :生成考勤打卡记录;
            endif
        }

        partition 考勤打卡记录数据处理 {
            :批量插入考勤打卡记录;
        }

    else(物流打卡班次匹配)
    :进行物流班次匹配规则;
    endif


endif

end
@enduml