@startuml
[*] --> 正常 : 打卡
[*] --> 早退 : 打卡
[*] --> 正常可提加班: 打卡
[*] --> 未打卡
未打卡 --> 旷工
正常可提加班 --> 正常已提加班 : 异常考勤申述
未打卡 --> 有申请早退 : 异常考勤申述
未打卡 --> 正常 : 异常考勤申述
未打卡 --> 正常已提加班 : 异常考勤申述
旷工 --> 有申请早退 : 异常考勤申述
旷工 --> 正常 : 异常考勤申述
旷工 --> 正常已提加班 : 异常考勤申述
早退 --> 有申请早退 : 异常考勤申述
早退 --> 正常 : 异常考勤申述
早退 --> 正常已提加班 : 异常考勤申述
旷工 --> [*]
早退 --> [*]
正常 --> [*]
有申请早退 --> [*]
正常已提加班 --> [*]
@enduml